# Generated by Django 4.2.4 on 2023-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blog_number_of_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак публикации'),
        ),
    ]
